"use client";

import { useMemo, useState } from "react";

const START_SCORE = 501;
type CpuLevel = 45 | 55 | 65;
type LegsToWin = 3 | 5 | 7 | 9;
type BullScore = 0 | 25 | 50;
type Props = { onComplete: (result: { metrics: Record<string, number>; details: Record<string, unknown> }) => void };
const IMPOSSIBLE_CHECKOUTS = new Set([169,168,166,165,163,162,159]);

function isCheckoutable(n:number){return n>=2&&n<=170&&!IMPOSSIBLE_CHECKOUTS.has(n)}
function cpuCheckoutChance(r:number,l:CpuLevel){if(!isCheckoutable(r))return 0;const b=l===45?.1:l===55?.16:.23;const d=r<=40?1.5:r<=80?1:r<=120?.65:.35;return Math.min(.55,Math.max(.02,b*d*(.5+Math.random()*1.1)))}
function cpuVisit(l:CpuLevel,r:number){if(Math.random()<cpuCheckoutChance(r,l))return{closed:true,scored:r,remaining:0};const spread=l===45?38:l===55?34:30;let s=Math.max(0,Math.min(180,Math.round(l+(Math.random()+Math.random()-1)*spread)));if(s>r||r-s===1)s=Math.min(s,Math.max(0,r-2));return{closed:false,scored:s,remaining:r-s}}
function cpuBull(l:CpuLevel):BullScore{const x=Math.random();const red=l===45?.05:l===55?.08:.12;const green=l===45?.18:l===55?.23:.28;return x<red?50:x<red+green?25:0}

export default function Practice501VsCpuTraining({onComplete}:Props){
 const[started,setStarted]=useState(false),[finished,setFinished]=useState(false),[cpuLevel,setCpuLevel]=useState<CpuLevel>(55),[legsToWin,setLegsToWin]=useState<LegsToWin>(5),[rule42,setRule42]=useState(true);
 const[playerRemaining,setPlayerRemaining]=useState(501),[cpuRemaining,setCpuRemaining]=useState(501),[playerLegs,setPlayerLegs]=useState(0),[cpuLegs,setCpuLegs]=useState(0),[legNumber,setLegNumber]=useState(1),[input,setInput]=useState(""),[playerPoints,setPlayerPoints]=useState(0),[playerVisits,setPlayerVisits]=useState(0),[legPlayerVisits,setLegPlayerVisits]=useState(0),[legCpuVisits,setLegCpuVisits]=useState(0),[bullMode,setBullMode]=useState(false),[message,setMessage]=useState("Du starter første leg.");
 const avg=useMemo(()=>playerVisits?playerPoints/playerVisits:0,[playerPoints,playerVisits]);
 function complete(p:number,c:number,pts:number,v:number){setFinished(true);onComplete({metrics:{score:p,won:p>c?1:0,playerLegs:p,cpuLegs:c,threeDartAverage:v?pts/v:0,cpuLevel,legsToWin},details:{startScore:501,cpuLevel,legsToWin,rule42,playerLegs:p,cpuLegs:c}})}
 function winLeg(who:"player"|"cpu",pts=playerPoints,v=playerVisits){const p=playerLegs+(who==="player"?1:0),c=cpuLegs+(who==="cpu"?1:0);setPlayerLegs(p);setCpuLegs(c);if(p>=legsToWin||c>=legsToWin){complete(p,c,pts,v);return}startNextLeg(legNumber+1,p,c,pts,v)}
 function startNextLeg(n:number,p:number,c:number,pts:number,v:number){setPlayerRemaining(501);setCpuRemaining(501);setLegPlayerVisits(0);setLegCpuVisits(0);setBullMode(false);setLegNumber(n);setInput("");if(n%2===0){const cpu=cpuVisit(cpuLevel,501);if(cpu.closed){setCpuLegs(c+1);if(c+1>=legsToWin){complete(p,c+1,pts,v);return}startNextLeg(n+1,p,c+1,pts,v);return}setCpuRemaining(cpu.remaining);setLegCpuVisits(1);setMessage(`CPU startede med ${cpu.scored}. Din tur.`)}else setMessage("Du starter dette leg.")}
 function resolve42(pRemain:number,cRemain:number,pts:number,v:number){if(pRemain<cRemain){winLeg("player",pts,v);return true}if(cRemain<pRemain){winLeg("cpu",pts,v);return true}setBullMode(true);setMessage("42 pile og samme remaining. Én pil på Bull hver.");return true}
 function score(){if(!started||finished||bullMode)return;const s=parseInt(input,10);if(!Number.isFinite(s)||s<0||s>180){setMessage("Indtast en score fra 0 til 180.");return}if(playerRemaining-s===0){setMessage("Brug Lukket, når du checker ud.");return}const bust=s>playerRemaining||playerRemaining-s===1;const eff=bust?0:s;const pr=bust?playerRemaining:playerRemaining-s;const pts=playerPoints+eff,v=playerVisits+1,lp=legPlayerVisits+1;setPlayerPoints(pts);setPlayerVisits(v);setLegPlayerVisits(lp);setPlayerRemaining(pr);setInput("");const cpu=cpuVisit(cpuLevel,cpuRemaining);const lc=legCpuVisits+1;setLegCpuVisits(lc);if(cpu.closed){winLeg("cpu",pts,v);return}setCpuRemaining(cpu.remaining);if(rule42&&lp>=14&&lc>=14){resolve42(pr,cpu.remaining,pts,v);return}setMessage(`${bust?"Bust":`Du scorede ${s}`}. CPU scorede ${cpu.scored}. Din tur.`)}
 function checkout(){if(!started||finished||bullMode)return;if(!isCheckoutable(playerRemaining)){setMessage("Det er ikke en mulig checkout.");return}const pts=playerPoints+playerRemaining,v=playerVisits+1;setPlayerPoints(pts);setPlayerVisits(v);winLeg("player",pts,v)}
 function bull(value:BullScore){if(!bullMode)return;const cpu=cpuBull(cpuLevel);if(value>cpu){setMessage(`Du ${value} - CPU ${cpu}. Du vinder leget.`);setBullMode(false);winLeg("player");return}if(cpu>value){setMessage(`Du ${value} - CPU ${cpu}. CPU vinder leget.`);setBullMode(false);winLeg("cpu");return}setMessage(`Begge ${value}. Kast én ny pil på Bull.`)}
 if(!started)return <section className="rounded-3xl border border-white/10 bg-white/[0.04] p-5 sm:p-7"><div className="mx-auto max-w-xl text-center"><div className="text-sm font-semibold uppercase tracking-[.2em] text-orange-300">501 vs CPU</div><h2 className="mt-2 text-3xl font-bold text-white">Vælg kamp</h2><p className="mt-3 text-gray-300">Rigtige 501-legs mod CPU. Skiftende starter.</p><div className="mt-6 grid grid-cols-3 gap-2">{([45,55,65] as CpuLevel[]).map(x=><button key={x} onClick={()=>setCpuLevel(x)} className={`rounded-2xl p-3 font-black ${cpuLevel===x?"bg-orange-500":"bg-white/10"}`}>CPU {x}</button>)}</div><div className="mt-3 grid grid-cols-4 gap-2">{([3,5,7,9] as LegsToWin[]).map(x=><button key={x} onClick={()=>setLegsToWin(x)} className={`rounded-2xl p-3 font-black ${legsToWin===x?"bg-orange-500":"bg-white/10"}`}>FT{x}</button>)}</div><button onClick={()=>setRule42(!rule42)} className={`mt-3 w-full rounded-2xl p-3 font-bold ${rule42?"bg-emerald-500/20 text-emerald-300":"bg-white/10 text-gray-300"}`}>42-dart-regel: {rule42?"ON":"OFF"}</button><button onClick={()=>setStarted(true)} className="mt-5 rounded-2xl bg-orange-500 px-8 py-4 text-lg font-bold">Start kamp</button></div></section>;
 return <section className="rounded-3xl border border-white/10 bg-white/[0.04] p-4 sm:p-7"><div className="mx-auto max-w-2xl"><div className="grid grid-cols-3 gap-2 text-center"><Stat label="Dig" value={`${playerLegs} legs`}/><Stat label="Leg" value={legNumber}/><Stat label={`CPU ${cpuLevel}`} value={`${cpuLegs} legs`}/></div><div className="mt-5 grid grid-cols-2 gap-3 text-center"><Score who="Dig" value={playerRemaining}/><Score who="CPU" value={cpuRemaining}/></div>{bullMode?<div className="mt-5 rounded-2xl bg-black/20 p-5 text-center"><h3 className="text-xl font-black">Bull shootout</h3><p className="mt-2 text-sm text-gray-400">Registrer din ene pil.</p><div className="mt-4 grid grid-cols-3 gap-2"><button onClick={()=>bull(50)} className="rounded-2xl bg-red-600 p-4 font-black">Rød · 50</button><button onClick={()=>bull(25)} className="rounded-2xl bg-emerald-600 p-4 font-black">Grøn · 25</button><button onClick={()=>bull(0)} className="rounded-2xl bg-gray-700 p-4 font-black">Udenfor · 0</button></div></div>:<div className="mt-5 rounded-2xl bg-black/20 p-4"><input inputMode="numeric" value={input} onChange={e=>setInput(e.target.value.replace(/[^0-9]/g,"").slice(0,3))} onKeyDown={e=>{if(e.key==="Enter")score()}} placeholder="0-180" className="w-full rounded-2xl border border-gray-700 bg-gray-950 px-4 py-4 text-center text-2xl font-black"/><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={score} className="rounded-2xl bg-white p-4 font-black text-gray-950">Score</button><button onClick={checkout} className="rounded-2xl bg-emerald-500 p-4 font-black">Lukket</button></div></div>}<div className="mt-4 grid grid-cols-3 gap-2 text-center"><Stat label="3-pils snit" value={avg.toFixed(1)}/><Stat label="Dine pile i leg" value={legPlayerVisits*3}/><Stat label="Først til" value={legsToWin}/></div><p className="mt-4 text-center text-sm font-semibold text-gray-400">{message}</p></div></section>
}
function Stat({label,value}:{label:string,value:string|number}){return <div className="rounded-2xl bg-black/20 p-3"><div className="text-xs uppercase text-gray-400">{label}</div><div className="mt-1 text-xl font-black">{value}</div></div>}
function Score({who,value}:{who:string,value:number}){return <div className="rounded-3xl bg-black/25 p-5"><div className="text-xs font-black uppercase text-gray-400">{who}</div><div className="mt-2 text-6xl font-black tabular-nums">{value}</div></div>}
