"use client";

import { useMemo, useState } from "react";

import MasterScoreInput from "@/components/scoring/MasterScoreInput";
import TrainingPlayBoard from "@/components/training/TrainingPlayBoard";

type CpuLevel = 45 | 55 | 65;
type Mode = "solo" | "cpu";
type Props = {
  title: string;
  startScore: 501 | 170;
  mode: Mode;
  cpuLevel?: CpuLevel;
  legsToWin?: number;
  soloAttempts?: number;
  maxDartsPerAttempt?: number;
  trackEntryAndDoubles?: boolean;
  onComplete: (result: { metrics: Record<string, number>; details: Record<string, unknown> }) => void | Promise<void>;
};
type Player = { remaining:number; legs:number; points:number; visits:number; checkoutAttempts:number; checkouts:number; highestCheckout:number; oneEighties:number; recent:number[]; legVisits:number };
type Snapshot = { player:Player; cpu:Player; turn:"player"|"cpu"; leg:number };
const IMPOSSIBLE = new Set([169,168,166,165,163,162,159]);
const QUICK_LEFT=[26,41,45,100], QUICK_RIGHT=[60,81,85,140], ROWS=[[1,2,3],[4,5,6],[7,8,9]];
function checkoutable(n:number){return n>=2&&n<=170&&!IMPOSSIBLE.has(n)}
function fresh(start:number):Player{return{remaining:start,legs:0,points:0,visits:0,checkoutAttempts:0,checkouts:0,highestCheckout:0,oneEighties:0,recent:[],legVisits:0}}
function cpuVisit(level:CpuLevel,remaining:number){const chance=checkoutable(remaining)?(level===45?.08:level===55?.14:.21):0;if(Math.random()<chance)return{score:remaining,closed:true};const spread=level===45?38:level===55?34:30;let score=Math.max(0,Math.min(180,Math.round(level+(Math.random()+Math.random()-1)*spread)));if(score>remaining||remaining-score===1||remaining-score===0)score=Math.max(0,remaining-2);return{score,closed:false}}

export default function TrainingMatchScorer({title,startScore,mode,cpuLevel=55,legsToWin=1,soloAttempts=1,maxDartsPerAttempt=9,trackEntryAndDoubles=false,onComplete}:Props){
 const[player,setPlayer]=useState(()=>fresh(startScore)); const[cpu,setCpu]=useState(()=>fresh(startScore));
 const[input,setInput]=useState(""); const[parts,setParts]=useState<number[]>([]); const[message,setMessage]=useState(""); const[history,setHistory]=useState<Snapshot[]>([]);
 const[attempt,setAttempt]=useState(1); const[entryDarts,setEntryDarts]=useState<number|null>(null); const[pendingEntry,setPendingEntry]=useState(false); const[pendingMiss,setPendingMiss]=useState(false); const[pendingCheckout,setPendingCheckout]=useState(false); const[checkoutDarts,setCheckoutDarts]=useState<number|null>(null); const[finished,setFinished]=useState(false); const[leg,setLeg]=useState(1);
 const total=parts.reduce((a,b)=>a+b,0)+(input?Number(input):0); const avg=player.visits?player.points/player.visits:0; const cpuAvg=cpu.visits?cpu.points/cpu.visits:0;
 const showBustMiss=!finished&&!pendingMiss&&!pendingCheckout&&player.remaining<=170&&!input&&!parts.length;
 const needed=mode==="solo"?soloAttempts:legsToWin;
 function remember(){setHistory(h=>[...h,{player:{...player,recent:[...player.recent]},cpu:{...cpu,recent:[...cpu.recent]},turn:"player",leg}])}
 function clear(){setInput("");setParts([])}
 function digit(n:number){if(finished||pendingMiss||pendingCheckout)return;const next=input+n;if(Number(next)<=180&&parts.reduce((a,b)=>a+b,0)+Number(next)<=180)setInput(next)}
 function choose(n:number){if(parts.reduce((a,b)=>a+b,0)+n<=180)setInput(String(n))}
 function plus(){if(!input)return;const n=Number(input);if(parts.reduce((a,b)=>a+b,0)+n<=180){setParts(p=>[...p,n]);setInput("")}}
 function nextLeg(p:Player,c:Player){const n=leg+1;setLeg(n);setPlayer({...p,remaining:startScore,legVisits:0,recent:[]});setCpu({...c,remaining:startScore,legVisits:0,recent:[]});setMessage(n%2===0&&mode==="cpu"?"CPU starter leget.":"Du starter leget.");if(n%2===0&&mode==="cpu")setTimeout(()=>runCpu({...c,remaining:startScore,legVisits:0,recent:[]},{...p,remaining:startScore,legVisits:0,recent:[]}),250)}
 async function complete(p:Player,c:Player){setFinished(true);await onComplete({metrics:{score:mode==="solo"&&soloAttempts>1?p.checkouts:(mode==="solo"?(p.visits?p.points/p.visits:0):p.legs),checkouts:p.checkouts,checkoutAttempts:p.checkoutAttempts,checkoutPercent:p.checkoutAttempts?p.checkouts/p.checkoutAttempts*100:0,won:mode==="solo"?1:(p.legs>c.legs?1:0),playerLegs:p.legs,cpuLegs:c.legs,threeDartAverage:p.visits?p.points/p.visits:0,cpuLevel:mode==="cpu"?cpuLevel:0,visits:p.visits,darts:p.visits*3,checkout:p.highestCheckout,highestVisit:Math.max(0,...p.recent)},details:{startScore,mode,cpuLevel:mode==="cpu"?cpuLevel:undefined,legsToWin:needed,playerLegs:p.legs,cpuLegs:c.legs}})}
 function nextSoloAttempt(p:Player){if(attempt>=soloAttempts){setPlayer(p);void complete(p,cpu);return}setAttempt(a=>a+1);setPlayer({...p,remaining:startScore,legVisits:0,recent:[]});setMessage("");}
 function winPlayer(darts:number){const checkout=player.remaining;const p={...player,remaining:0,legs:player.legs+1,points:player.points+checkout,visits:player.visits+1,legVisits:player.legVisits+1,checkoutAttempts:player.checkoutAttempts+darts,checkouts:player.checkouts+1,highestCheckout:Math.max(player.highestCheckout,checkout),recent:[...player.recent,checkout].slice(-5)};setPendingCheckout(false);setCheckoutDarts(null);clear();if(mode==="solo"&&soloAttempts>1){nextSoloAttempt(p)}else if(p.legs>=needed){setPlayer(p);void complete(p,cpu)}else nextLeg(p,cpu)}
 function runCpu(c=cpu,p=player){if(mode!=="cpu"||finished)return;const v=cpuVisit(cpuLevel,c.remaining);const nc={...c,remaining:v.closed?0:c.remaining-v.score,points:c.points+v.score,visits:c.visits+1,legVisits:c.legVisits+1,checkouts:c.checkouts+(v.closed?1:0),checkoutAttempts:c.checkoutAttempts+(checkoutable(c.remaining)?1:0),highestCheckout:v.closed?Math.max(c.highestCheckout,c.remaining):c.highestCheckout,recent:[...c.recent,v.score].slice(-5)};setCpu(nc);if(v.closed){nc.legs+=1;if(nc.legs>=needed){void complete(p,nc)}else nextLeg(p,nc);return}setMessage(`CPU scorede ${v.score}. Din tur.`)}
 function enterScore(directScore?:number){if(finished||pendingMiss||pendingCheckout)return;const score=directScore ?? total;if(directScore===undefined&&!input&&!parts.length)return;if(score<0||score>180)return;remember();const next=player.remaining-score;if(next<0||next===1){const p={...player,visits:player.visits+1,legVisits:player.legVisits+1,recent:[...player.recent,0].slice(-5)};setPlayer(p);clear();setMessage("Bust — ingen score.");setTimeout(()=>runCpu(cpu,p),200);return}if(next===0){if(!checkoutable(player.remaining)){clear();setMessage("Bust — double out.");setTimeout(()=>runCpu(cpu,player),200);return}clear();if(trackEntryAndDoubles){setPendingEntry(true);setEntryDarts(null)}else{setPendingCheckout(true);setCheckoutDarts(null)}return}const p={...player,remaining:next,points:player.points+score,visits:player.visits+1,legVisits:player.legVisits+1,oneEighties:player.oneEighties+(score===180?1:0),recent:[...player.recent,score].slice(-5)};clear();setMessage("");if(mode==="solo"&&soloAttempts>1&&p.legVisits>=Math.ceil(maxDartsPerAttempt/3)){nextSoloAttempt(p)}else{setPlayer(p);if(mode==="cpu")setTimeout(()=>runCpu(cpu,p),200)}}
 function saveEntry(){if(entryDarts===null)return;setPendingEntry(false);if(entryDarts===1){winPlayer(1);return}setPendingCheckout(true);setCheckoutDarts(null)}
 function saveMiss(){if(checkoutDarts===null)return;const p={...player,visits:player.visits+1,legVisits:player.legVisits+1,checkoutAttempts:player.checkoutAttempts+checkoutDarts,recent:[...player.recent,0].slice(-5)};setPendingMiss(false);setCheckoutDarts(null);if(mode==="solo"&&soloAttempts>1&&p.legVisits>=Math.ceil(maxDartsPerAttempt/3)){nextSoloAttempt(p)}else{setPlayer(p);if(mode==="cpu")setTimeout(()=>runCpu(cpu,p),200)}}
 function undo(){const s=history.at(-1);if(!s)return;setPlayer(s.player);setCpu(s.cpu);setLeg(s.leg);setHistory(h=>h.slice(0,-1));setPendingMiss(false);setPendingEntry(false);setEntryDarts(null);setPendingCheckout(false);setCheckoutDarts(null);clear();setMessage("")}
 const stats=useMemo(()=>({close:player.checkoutAttempts?Math.round(player.checkouts/player.checkoutAttempts*100):0}),[player]);
 const card=(name:string,p:Player,index:0|1)=><div className={`rounded-2xl border-2 ${index===0?"border-blue-600":"border-red-600"} bg-gray-900 p-3`}><div className={`text-sm font-semibold ${index===0?"text-blue-400":"text-red-400"}`}>{index===0?"SPILLER 1":"SPILLER 2"}</div><div className="mt-1 text-2xl font-bold">{name}</div><div className="mt-1 flex items-center justify-between gap-3"><div className="text-6xl font-bold tabular-nums">{p.remaining}</div><div className="min-w-24 rounded-xl bg-black/20 px-3 py-2 text-center"><div className="text-xs font-bold text-gray-400">SENESTE 5</div>{p.recent.length?p.recent.map((x,i)=><div key={i} className="text-sm font-bold">{x}</div>):<div className="text-gray-600">—</div>}<div className="mt-2 text-xs text-gray-400">{mode==="solo"&&soloAttempts>1 ? <>FORSØG <b className="text-white">{attempt} / {soloAttempts}</b></> : <>SNIT <b className="text-white">{(p.visits?p.points/p.visits:0).toFixed(2)}</b></>}</div></div></div><div className="mt-4 grid grid-cols-3 border-t border-gray-800 pt-3 text-center text-xs text-gray-400"><div>SNIT<br/><b>{(p.visits?p.points/p.visits:0).toFixed(2)}</b></div><div>LUKKET / FORSØGT<br/><b>{p.checkouts} / {p.checkoutAttempts}</b></div><div>180&apos;ERE<br/><b>{p.oneEighties}</b></div></div></div>;
 if(mode==="solo"&&soloAttempts>1&&!finished)return <TrainingPlayBoard title={title} status={`FORSØG ${attempt} / ${soloAttempts}`} option={`${maxDartsPerAttempt} PILE`} score={player.remaining} recent={player.recent} average={avg} controls={<>{pendingEntry?<Prompt title="INDGANG" text="Hvor mange pile brugte du på indgang?" value={entryDarts} setValue={setEntryDarts} save={saveEntry} saveText="GEM INDGANG" noZero/>:pendingMiss?<Prompt title="BUST / MISS" text="Hvor mange pile brugt på double?" value={checkoutDarts} setValue={setCheckoutDarts} save={saveMiss} saveText="GEM BUST / MISS"/>:pendingCheckout?<Prompt title="LUKNING" text="Hvor mange pile brugte du på double?" value={checkoutDarts} setValue={setCheckoutDarts} save={()=>checkoutDarts&&winPlayer(checkoutDarts)} saveText="GEM DOUBLE" noZero/>:<MasterScoreInput input={input} parts={parts} onInputChange={setInput} onPartsChange={setParts} onEnter={(score)=>enterScore(score)} onUndo={undo} canUndo={history.length>0} extraAction={showBustMiss?<button onClick={()=>{remember();setPendingMiss(true)}} className="rounded-2xl border border-yellow-600 bg-yellow-500/10 text-xl font-bold text-yellow-300">BUST / MISS</button>:<div/>}/>}</>} />;
 return <div className="space-y-3"><div className={`grid gap-3 ${mode==="cpu"?"md:grid-cols-[minmax(0,1fr)_220px_minmax(0,1fr)]":"grid-cols-1"}`}>{card("Dig",player,0)}{mode==="cpu"&&<div className="rounded-2xl border border-gray-800 bg-gray-900 p-5 text-center"><div className="text-sm text-gray-400">{title}</div><div className="mt-4 text-4xl font-bold"><span className="text-blue-400">{player.legs}</span><span className="text-gray-600"> – </span><span className="text-red-400">{cpu.legs}</span></div><div className="mt-6 text-xs text-gray-500">LEG {leg}</div></div>}{mode==="cpu"&&card(`CPU ${cpuLevel}`,cpu,1)}</div>
 {pendingEntry&&<Prompt title="INDGANG" text="Hvor mange pile brugte du på indgang?" value={entryDarts} setValue={setEntryDarts} save={saveEntry} saveText="GEM INDGANG" noZero/>}
 {pendingMiss&&<Prompt title="BUST / MISS" text="Hvor mange pile brugt på double?" value={checkoutDarts} setValue={setCheckoutDarts} save={saveMiss} saveText="GEM BUST / MISS"/>}
 {pendingCheckout&&<Prompt title="LUKNING" text="Hvor mange pile brugte du på double?" value={checkoutDarts} setValue={setCheckoutDarts} save={()=>checkoutDarts&&winPlayer(checkoutDarts)} saveText="GEM DOUBLE" noZero/>}
 {!pendingEntry&&!pendingMiss&&!pendingCheckout&&!finished&&<MasterScoreInput input={input} parts={parts} onInputChange={setInput} onPartsChange={setParts} onEnter={()=>enter()} onUndo={undo} canUndo={history.length>0} extraAction={showBustMiss?<button onClick={()=>{remember();setPendingMiss(true)}} className="rounded-2xl border border-yellow-600 bg-yellow-500/10 text-xl font-bold text-yellow-300">BUST / MISS</button>:<div/>}/>}
 {finished&&<div className="rounded-2xl border border-emerald-600 bg-emerald-500/10 p-5 text-center text-xl font-bold text-emerald-300">{mode==="solo"?`Leg afsluttet · ${avg.toFixed(1)} i snit`:`Kamp afsluttet · ${player.legs}-${cpu.legs}`}</div>}{message&&<p className="text-center text-sm font-semibold text-gray-400">{message}</p>}</div>
}
function Prompt({title,text,value,setValue,save,saveText,noZero=false}:{title:string;text:string;value:number|null;setValue:(v:number)=>void;save:()=>void;saveText:string;noZero?:boolean}){return <div className="rounded-2xl border border-blue-600 bg-gray-900 p-5 text-center"><div className="text-sm text-blue-400">{title}</div><div className="mt-1 text-2xl font-bold">{text}</div><div className="mt-4 grid grid-cols-4 gap-2">{[0,1,2,3].map(x=><button key={x} disabled={noZero&&x===0} onClick={()=>setValue(x)} className={`rounded-xl border py-5 text-2xl font-bold disabled:opacity-30 ${value===x?"border-blue-500 bg-blue-500/20":"border-gray-800 bg-gray-900"}`}>{x}</button>)}</div><button onClick={save} disabled={value===null||(noZero&&value===0)} className="mt-3 w-full rounded-xl bg-green-500 py-5 text-xl font-bold text-black disabled:opacity-40">{saveText}</button></div>}
function Mini({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl bg-black/20 p-3"><div className="text-xs uppercase text-gray-400">{label}</div><div className="mt-1 text-xl font-black">{value}</div></div>}
