"use client";
import{useEffect,useMemo,useState}from"react";import{saveCompletedMatch}from"@/lib/matchStore";
type P={name:string;remaining:number;legs:number;totalScored:number;entries:number;checkouts:number;checkoutAttempts:number;oneEighties:number;lastInput:number|null;legDarts:number;fastestLegDarts:number|null};type PC={score:number;remaining:number;dartsEntered:number};type Props={matchId:string;player1:string;player2:string;bestOfLegs?:number;board?:number|null;pool?:string|null;round?:number|null};
const rows=[[1,2,3],[4,5,6],[7,8,9]],ql=[26,41,45,100],qr=[60,81,85,140];const fresh=(name:string):P=>({name,remaining:501,legs:0,totalScored:0,entries:0,checkouts:0,checkoutAttempts:0,oneEighties:0,lastInput:null,legDarts:0,fastestLegDarts:null});
export default function MatchScorer({matchId,player1,player2,bestOfLegs=3,board=null,pool=null,round=null}:Props){const[ps,setPs]=useState<P[]>([fresh(player1),fresh(player2)]),[cp,setCp]=useState<0|1>(0),[ds,setDs]=useState<number[]>([]),[hist,setHist]=useState<P[][]>([]),[msg,setMsg]=useState(""),[pc,setPc]=useState<PC|null>(null),[cd,setCd]=useState(""),[saved,setSaved]=useState(false),cur=ps[cp],sum=ds.reduce((a,b)=>a+b,0),need=Math.ceil(bestOfLegs/2),winner=useMemo(()=>ps.find(p=>p.legs>=need),[ps,need]);
function complete(){if(!winner)return null;return{id:matchId,player1:ps[0].name,player2:ps[1].name,winner:winner.name,score1:ps[0].legs,score2:ps[1].legs,bestOfLegs,board,pool,round,status:"finished" as const,finishedAt:new Date().toISOString(),players:ps.map(p=>({name:p.name,legs:p.legs,totalScored:p.totalScored,entries:p.entries,average:p.entries?p.totalScored/p.entries:0,checkouts:p.checkouts,checkoutAttempts:p.checkoutAttempts,checkoutPercent:p.checkoutAttempts?Math.round(p.checkouts/p.checkoutAttempts*100):0,oneEighties:p.oneEighties,fastestLegDarts:p.fastestLegDarts}))}}
useEffect(()=>{if(!winner||saved)return;const m=complete();if(m){saveCompletedMatch(m);setSaved(true)}},[winner,saved]);
const clear=()=>{if(!pc){setDs([]);setMsg("")}},dart=(n:number)=>{if(winner||pc||ds.length>=3||n<0||n>60||sum+n>180)return;setDs(v=>[...v,n]);setMsg("")},quick=(n:number)=>{if(!winner&&!pc)setDs([n])};
function finish(score:number,rem:number,attempts=0,darts=3){setPs(v=>v.map((p,i)=>i===cp?{...p,remaining:rem,totalScored:p.totalScored+score,entries:p.entries+1,checkoutAttempts:p.checkoutAttempts+attempts,oneEighties:p.oneEighties+(score===180?1:0),lastInput:score,legDarts:p.legDarts+darts}:p));setDs([]);setCp(cp?0:1);setMsg("")}
function enter(){if(!ds.length||winner||pc)return;const score=sum,rem=cur.remaining-score,n=ds.length;setHist(v=>[...v,ps.map(p=>({...p}))]);if(rem<0||rem===1){setDs([]);setCp(cp?0:1);setMsg("Bust — ingen score.");return}if(rem===0){if(score<2||score>170){setDs([]);setCp(cp?0:1);setMsg("Bust — double out.");return}setPc({score,remaining:0,dartsEntered:n});setCd("");setDs([]);return}if(rem<50){setPc({score,remaining:rem,dartsEntered:n});setCd("");setDs([]);return}finish(score,rem,0,n)}
function save(){const n=Number(cd);if(!pc||!Number.isInteger(n)||n<1||n>3||(pc.dartsEntered>0&&n>pc.dartsEntered))return;const{score,remaining}=pc;if(remaining===0)setPs(v=>v.map((p,i)=>i!==cp?p:{...p,remaining:501,legs:p.legs+1,totalScored:p.totalScored+score,entries:p.entries+1,checkouts:p.checkouts+1,checkoutAttempts:p.checkoutAttempts+n,oneEighties:p.oneEighties+(score===180?1:0),lastInput:score,legDarts:0,fastestLegDarts:p.fastestLegDarts===null?p.legDarts+n:Math.min(p.fastestLegDarts,p.legDarts+n)}));else{finish(score,remaining,n,pc.dartsEntered||3);setPc(null);setCd("");return}setPc(null);setCd("");setCp(cp?0:1);setMsg("")}
function undo(){if(pc)return;const p=hist.at(-1);if(!p)return;setPs(p.map(x=>({...x})));setHist(v=>v.slice(0,-1));setDs([]);setMsg("");setSaved(false)}
useEffect(()=>{const k=(e:KeyboardEvent)=>{if(e.key==="Enter"){e.preventDefault();pc?save():enter()}else if(!pc&&e.key==="Escape")clear();else if(!pc&&/^\\d$/.test(e.key))dart(+e.key)};window.addEventListener("keydown",k);return()=>window.removeEventListener("keydown",k)},[ds,sum,pc,winner,cur,cp,ps,hist]);
const stat=ps.map(p=>({a:p.entries?p.totalScored/p.entries:0,c:p.checkoutAttempts?Math.round(p.checkouts/p.checkoutAttempts*100):0}));const card=(p:P,i:0|1)=><div className={`rounded-2xl border-2 ${i?"border-red-600":"border-blue-600"} bg-gray-900 p-5`}><div className={`text-sm font-semibold ${i?"text-red-400":"text-blue-400"}`}>SPILLER {i+1}</div><div className="mt-1 text-2xl font-bold">{p.name}</div><div className="text-xs text-gray-500">Sidste indtastning: {p.lastInput??"—"}</div><div className="mt-2 flex items-center justify-between gap-4"><div className="text-7xl font-bold tabular-nums">{p.remaining}</div><div className={`rounded-xl px-5 py-3 text-center ${i?"bg-red-500/10 text-red-400":"bg-blue-500/10 text-blue-400"}`}><div className="text-xs">LEGS</div><div className="text-3xl font-bold">{p.legs}</div></div></div><div className="mt-4 grid grid-cols-5 border-t border-gray-800 pt-3 text-center text-xs text-gray-400"><div>SNIT / LEG<br/><b>{stat[i].a.toFixed(2)}</b></div><div>SNIT / KAMP<br/><b>{stat[i].a.toFixed(2)}</b></div><div>LUKKET / FORSØGT<br/><b>{p.checkouts} / {p.checkoutAttempts}</b></div><div>LUKKE %<br/><b>{stat[i].c}%</b></div><div>180&apos;ERE<br/><b>{p.oneEighties}</b></div></div></div>;
return <div className="space-y-4"><div className="grid gap-3 md:grid-cols-[minmax(0,1fr)_260px_minmax(0,1fr)]">{card(ps[0],0)}<div className="rounded-2xl border border-gray-800 bg-gray-900 p-5 text-center"><div className="text-sm text-gray-400">LEGS · BEDST AF {bestOfLegs}</div><div className="mt-4 text-4xl font-bold"><span className="text-blue-400">{ps[0].legs}</span><span className="text-gray-600"> – </span><span className="text-red-400">{ps[1].legs}</span></div><div className="mt-8 text-sm text-gray-500">NÆSTE SPILLER</div><div className={`mt-1 text-xl font-bold ${cp?"text-red-400":"text-blue-400"}`}>{cur.name}</div></div>{card(ps[1],1)}</div>
{pc&&<div className="rounded-2xl border border-blue-600 bg-gray-900 p-5 text-center"><div className="text-sm text-blue-400">LUKNING</div><div className="mt-1 text-2xl font-bold">{pc.remaining===0?"Hvor mange pile brugte du på lukningen?":"Hvor mange pile brugte du på checkout-forsøget?"}</div><div className="mt-1 text-gray-400">Rest: {pc.remaining}</div><div className="mt-4 grid grid-cols-3 gap-2">{[1,2,3].map(n=><button key={n} onClick={()=>setCd(`${n}`)} disabled={n>(pc.dartsEntered||3)} className={`rounded-xl border py-5 text-2xl font-bold ${cd===`${n}`?"border-blue-500 bg-blue-500/20":"border-gray-800 bg-gray-900"} disabled:opacity-30`}>{n} {n===1?"PIL":"PILE"}</button>)}</div><button onClick={save} disabled={!cd} className="mt-3 w-full rounded-xl bg-green-500 py-5 text-xl font-bold text-black disabled:opacity-40">GEM LUKNING</button></div>}
<div className="grid grid-cols-[minmax(0,1fr)_110px] gap-2"><div className="flex min-h-[76px] items-center rounded-2xl border border-gray-800 bg-gray-900 px-6"><div><div className="flex flex-wrap gap-2 text-2xl font-bold">{ds.length?ds.map((d,i)=><span key={`${i}-${d}`} className="rounded-lg bg-gray-800 px-3 py-1">{d}</span>):<span className="text-gray-500">INDTAST PILE</span>}</div>{ds.length>0&&<div className="mt-1 text-sm text-gray-500">{ds.length}/3 pile · visit: {sum}</div>}</div></div><button onClick={clear} disabled={!!pc} className="rounded-2xl border border-gray-800 bg-gray-900 text-xl font-bold disabled:opacity-40">CLR</button></div>
<div className="grid grid-cols-5 gap-2"><div className="grid gap-2">{ql.map(s=><button key={s} onClick={()=>quick(s)} disabled={!!pc} className="rounded-xl border border-green-800 bg-green-500/10 py-5 text-2xl font-bold text-green-400 disabled:opacity-40">{s}</button>)}</div><div className="col-span-3 grid gap-2">{rows.map(r=><div key={r[0]} className="grid grid-cols-3 gap-2">{r.map(s=><button key={s} onClick={()=>dart(s)} disabled={!!pc||ds.length>=3} className="rounded-xl border border-gray-800 bg-gray-900 py-5 text-3xl font-bold disabled:opacity-40">{s}</button>)}</div>)}<div className="grid grid-cols-3 gap-2"><button onClick={()=>dart(0)} disabled={!!pc||ds.length>=3} className="rounded-xl border border-gray-800 bg-gray-900 py-5 text-3xl font-bold disabled:opacity-40">0</button><button onClick={()=>quick(180)} disabled={!!pc} className="rounded-xl border border-purple-800 bg-purple-500/10 py-5 text-2xl font-bold text-purple-300 disabled:opacity-40">180</button><button onClick={enter} disabled={!ds.length||!!pc} className="rounded-xl bg-green-500 py-5 text-2xl font-bold text-black disabled:opacity-40">ENTER</button></div></div><div className="grid gap-2">{qr.map(s=><button key={s} onClick={()=>quick(s)} disabled={!!pc} className="rounded-xl border border-green-800 bg-green-500/10 py-5 text-2xl font-bold text-green-400 disabled:opacity-40">{s}</button>)}</div></div>
<div className="grid grid-cols-2 gap-2"><button onClick={undo} disabled={!!pc} className="rounded-xl border border-red-900 bg-red-500/10 py-5 text-xl font-bold text-red-400 disabled:opacity-40">↶ UNDO</button><div className="flex items-center justify-center rounded-xl border border-gray-800 bg-gray-900 text-sm text-gray-500">PIL-FOR-PIL · ENTER FOR AT GEMME</div></div>{msg&&<div className="rounded-xl border border-yellow-800 bg-yellow-500/10 p-4 text-center font-semibold text-yellow-300">{msg}</div>}{winner&&<div className="rounded-2xl border border-green-600 bg-green-500/10 p-5 text-center"><div className="text-sm text-green-400">KAMP FÆRDIG</div><div className="mt-1 text-3xl font-bold">{winner.name} VINDER</div><div className="mt-1">{ps[0].legs} – {ps[1].legs}</div></div>}</div>}
