"use client";

import { createContext, useCallback, useContext, useEffect, useMemo, useState, useSyncExternalStore, ReactNode } from "react";
import type { ClubMatch } from "@/lib/matchEngine";
import { DEMO_CLUB_ID } from "@/data/clubs";
import { useClub } from "@/context/ClubContext";
import { getCurrentClubId } from "@/lib/currentClub";
import { getCompletedMatches, replaceCompletedMatchesFromSharedState } from "@/lib/matchStore";
import { saveLiveActiveSnapshotForClubNight } from "@/lib/liveActiveEngine";
import { syncSharedClubDataFromServer } from "@/lib/sharedClubDataClient";
import type { SharedClubNightState } from "@/lib/serverClubNightStateStore";

export type Pool = { name: string; players: string[] };

type KlubaftenContextType = {
  currentClubId: string; clubNights: ClubNight[]; activeClubNights: ClubNight[]; archivedClubNights: ClubNight[]; isSharedStateReady: boolean;
  currentClubNightId: string | null; currentClubNight: ClubNight | null; setCurrentClubNightId: (clubNightId: string | null) => void;
  createClubNight: (input: { name: string; date: string; boardCount?: number; handicapBoards?: number[] }) => ClubNight;
  updateClubNight: (clubNightId: string, update: (clubNight: ClubNight) => ClubNight) => void; deleteClubNight: (clubNightId: string) => void;
  selectedPlayers: string[]; setSelectedPlayers: (players: string[]) => void; pools: Pool[]; setPools: (pools: Pool[]) => void;
  matches: ClubMatch[]; setMatches: (matches: ClubMatch[]) => void; boardCount: number; setBoardCount: (count: number) => void;
  handicapBoards: number[]; setHandicapBoards: (boards: number[]) => void; isFinished: boolean; finishKlubaften: () => void;
  finishClubNight: (clubNightId?: string) => void; abortClubNight: (clubNightId?: string) => void;
};

const KlubaftenContext = createContext<KlubaftenContextType | undefined>(undefined);
const STORAGE_KEY = "hesteng.klubaftenState";
const STORAGE_CHANGE_EVENT = "hesteng.klubaftenStateChanged";
const SHARED_STATE_MIGRATION_KEY = "hesteng.sharedClubNightMigrated.v2";
const SHARED_STATE_API = "/api/club-night-state";
const SHARED_STATE_POLL_INTERVAL_MS = 5000;
export type ClubNightStatus = "active" | "finished" | "aborted";
export type ClubNight = { id: string; clubId?: string; name: string; date: string; status: ClubNightStatus; selectedPlayers: string[]; pools: Pool[]; matches: ClubMatch[]; boardCount: number; handicapBoards: number[]; createdAt: string; finishedAt?: string };
type LegacyKlubaftenSnapshot = { selectedPlayers?: string[]; pools?: Pool[]; matches?: ClubMatch[]; boardCount?: number; handicapBoards?: number[]; isFinished?: boolean };
export type KlubaftenSnapshot = { clubNights: ClubNight[]; currentClubNightId: string | null };
const EMPTY_CLUB_NIGHT: Omit<ClubNight, "id" | "name" | "date" | "status" | "createdAt" | "finishedAt"> = { selectedPlayers: [], pools: [], matches: [], boardCount: 13, handicapBoards: [] };
const DEFAULT_KLUBAFTEN: KlubaftenSnapshot = { clubNights: [], currentClubNightId: null };
let cachedRawSnapshot: string | null = null; let cachedSnapshot: KlubaftenSnapshot = DEFAULT_KLUBAFTEN; let pendingSharedPushRaw: string | null = null;
function createId() { if (typeof crypto !== "undefined" && "randomUUID" in crypto) return crypto.randomUUID(); return `club-night-${Date.now()}-${Math.random().toString(16).slice(2)}`; }
function todayIsoDate() { return new Date().toISOString().slice(0, 10); }
function normalizeClubNight(clubNight: Partial<ClubNight>, fallbackId = createId(), fallbackClubId = getCurrentClubId()): ClubNight { const id = clubNight.id ?? fallbackId; const clubId = clubNight.clubId ?? fallbackClubId; return { id, clubId, name: clubNight.name ?? "Klubaften", date: clubNight.date ?? todayIsoDate(), status: clubNight.status ?? "active", selectedPlayers: clubNight.selectedPlayers ?? [], pools: clubNight.pools ?? [], matches: (clubNight.matches ?? []).map((match) => ({ ...match, clubId: match.clubId ?? clubId, clubNightId: match.clubNightId ?? id })), boardCount: clubNight.boardCount ?? 13, handicapBoards: clubNight.handicapBoards ?? [], createdAt: clubNight.createdAt ?? new Date().toISOString(), finishedAt: clubNight.finishedAt }; }
function migrateLegacySnapshot(snapshot: LegacyKlubaftenSnapshot): KlubaftenSnapshot { const has = (snapshot.selectedPlayers?.length ?? 0) > 0 || (snapshot.pools?.length ?? 0) > 0 || (snapshot.matches?.length ?? 0) > 0; if (!has) return DEFAULT_KLUBAFTEN; const id = "legacy-club-night"; const night = normalizeClubNight({ id, clubId: DEMO_CLUB_ID, name: "Migreret klubaften", date: todayIsoDate(), status: snapshot.isFinished ? "finished" : "active", selectedPlayers: snapshot.selectedPlayers, pools: snapshot.pools, matches: snapshot.matches, boardCount: snapshot.boardCount, handicapBoards: snapshot.handicapBoards, createdAt: new Date().toISOString(), finishedAt: snapshot.isFinished ? new Date().toISOString() : undefined }, id, DEMO_CLUB_ID); return { clubNights: [night], currentClubNightId: id }; }
function normalizeSnapshot(snapshot: Partial<KlubaftenSnapshot> & LegacyKlubaftenSnapshot): KlubaftenSnapshot { if (!Array.isArray(snapshot.clubNights)) return migrateLegacySnapshot(snapshot); const clubNights = snapshot.clubNights.map((n, i) => normalizeClubNight(n, `club-night-${i + 1}`, n.clubId ?? DEMO_CLUB_ID)); const currentExists = clubNights.some((n) => n.id === snapshot.currentClubNightId); const first = clubNights.find((n) => n.status === "active") ?? clubNights[0] ?? null; return { clubNights, currentClubNightId: currentExists ? snapshot.currentClubNightId ?? null : first?.id ?? null }; }
function getStoredKlubaften(): KlubaftenSnapshot { if (typeof window === "undefined") return DEFAULT_KLUBAFTEN; try { const raw = window.localStorage.getItem(STORAGE_KEY); if (raw === cachedRawSnapshot) return cachedSnapshot; if (!raw) return DEFAULT_KLUBAFTEN; const parsed = JSON.parse(raw); cachedRawSnapshot = raw; cachedSnapshot = parsed && typeof parsed === "object" ? normalizeSnapshot(parsed) : DEFAULT_KLUBAFTEN; return cachedSnapshot; } catch { return DEFAULT_KLUBAFTEN; } }
function sharedSnapshotHasClubNightData(snapshot: SharedClubNightState) { return snapshot.clubNights.length > 0 || snapshot.completedMatches.length > 0; }
function hasMigratedLocalSnapshotToShared() { if (typeof window === "undefined") return true; return window.localStorage.getItem(SHARED_STATE_MIGRATION_KEY) === "true"; }
function markLocalSnapshotMigratedToShared() { if (typeof window !== "undefined") window.localStorage.setItem(SHARED_STATE_MIGRATION_KEY, "true"); }
function hasLocalClubNightsMissingFromShared(local: KlubaftenSnapshot, shared: KlubaftenSnapshot) { const ids = new Set(shared.clubNights.map((n) => n.id)); return local.clubNights.some((n) => !ids.has(n.id)); }
function mergeLocalClubNightsIntoShared(local: KlubaftenSnapshot, shared: KlubaftenSnapshot): KlubaftenSnapshot { const ids = new Set(shared.clubNights.map((n) => n.id)); const missing = local.clubNights.filter((n) => !ids.has(n.id)); const currentClubNightId = shared.currentClubNightId ?? (local.currentClubNightId && missing.some((n) => n.id === local.currentClubNightId) ? local.currentClubNightId : null); return normalizeSnapshot({ clubNights: [...missing, ...shared.clubNights], currentClubNightId }); }
async function pushSharedKlubaftenSnapshot(snapshot: KlubaftenSnapshot, rawSnapshot: string, completedMatches = getCompletedMatches()) { pendingSharedPushRaw = rawSnapshot; try { const response = await fetch(SHARED_STATE_API, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ clubNights: snapshot.clubNights, currentClubNightId: snapshot.currentClubNightId, completedMatches }) }); return response.ok; } catch { return false; } finally { if (pendingSharedPushRaw === rawSnapshot) pendingSharedPushRaw = null; } }
function saveStoredKlubaften(snapshot: KlubaftenSnapshot, options: { syncShared?: boolean } = {}) { if (typeof window === "undefined") return; const normalized = normalizeSnapshot(snapshot); cachedRawSnapshot = JSON.stringify(normalized); cachedSnapshot = normalized; window.localStorage.setItem(STORAGE_KEY, cachedRawSnapshot); window.dispatchEvent(new Event(STORAGE_CHANGE_EVENT)); if (options.syncShared !== false) void pushSharedKlubaftenSnapshot(normalized, cachedRawSnapshot); }
function updateStoredKlubaften(update: (snapshot: KlubaftenSnapshot) => KlubaftenSnapshot) { const current = getStoredKlubaften(); const next = normalizeSnapshot(update(current)); if (JSON.stringify(current) !== JSON.stringify(next)) saveStoredKlubaften(next); }
function subscribeToKlubaften(callback: () => void) { if (typeof window === "undefined") return () => undefined; const handleStorage = (event: StorageEvent) => { if (event.key === STORAGE_KEY) callback(); }; window.addEventListener("storage", handleStorage); window.addEventListener(STORAGE_CHANGE_EVENT, callback); return () => { window.removeEventListener("storage", handleStorage); window.removeEventListener(STORAGE_CHANGE_EVENT, callback); }; }
export function KlubaftenProvider({ children }: { children: ReactNode }) {
  const snapshot = useSyncExternalStore(subscribeToKlubaften, getStoredKlubaften, () => DEFAULT_KLUBAFTEN); const [isSharedStateReady, setIsSharedStateReady] = useState(false); const { currentClubId } = useClub();
  useEffect(() => { let cancelled = false; async function sync() { try { await syncSharedClubDataFromServer(); const response = await fetch(SHARED_STATE_API, { cache: "no-store" }); if (!response.ok) { if (!cancelled) setIsSharedStateReady(true); return; } const sharedState = await response.json() as SharedClubNightState; if (cancelled) return; const local = getStoredKlubaften(); const localRaw = JSON.stringify(local); const shared = normalizeSnapshot({ clubNights: sharedState.clubNights, currentClubNightId: sharedState.currentClubNightId }); const sharedRaw = JSON.stringify(shared); if (!hasMigratedLocalSnapshotToShared() && hasLocalClubNightsMissingFromShared(local, shared)) { const migrated = mergeLocalClubNightsIntoShared(local, shared); const raw = JSON.stringify(migrated); const completed = [...(sharedState.completedMatches ?? []), ...getCompletedMatches()]; if (await pushSharedKlubaftenSnapshot(migrated, raw, completed)) { markLocalSnapshotMigratedToShared(); replaceCompletedMatchesFromSharedState(completed); saveStoredKlubaften(migrated, { syncShared: false }); } if (!cancelled) setIsSharedStateReady(true); return; } if (!sharedSnapshotHasClubNightData(sharedState) && local.clubNights.length > 0) { if (!hasMigratedLocalSnapshotToShared()) { if (await pushSharedKlubaftenSnapshot(local, localRaw)) markLocalSnapshotMigratedToShared(); if (!cancelled) setIsSharedStateReady(true); return; } replaceCompletedMatchesFromSharedState([]); if (sharedRaw !== localRaw) saveStoredKlubaften(shared, { syncShared: false }); if (!cancelled) setIsSharedStateReady(true); return; } replaceCompletedMatchesFromSharedState(sharedState.completedMatches ?? []); if (pendingSharedPushRaw && pendingSharedPushRaw !== sharedRaw) return; if (sharedRaw !== localRaw) saveStoredKlubaften(shared, { syncShared: false }); if (!cancelled) setIsSharedStateReady(true); } catch { if (!cancelled) setIsSharedStateReady(true); } } void sync(); const interval = window.setInterval(sync, SHARED_STATE_POLL_INTERVAL_MS); return () => { cancelled = true; window.clearInterval(interval); }; }, []);
  const scoped = useMemo(() => snapshot.clubNights.filter((n) => (n.clubId ?? DEMO_CLUB_ID) === currentClubId), [currentClubId, snapshot.clubNights]); const current = useMemo(() => scoped.find((n) => n.id === snapshot.currentClubNightId) ?? null, [scoped, snapshot.currentClubNightId]); const active = useMemo(() => scoped.filter((n) => n.status === "active"), [scoped]); const archived = useMemo(() => scoped.filter((n) => n.status !== "active"), [scoped]);
  const setCurrentClubNightId = useCallback((id: string | null) => updateStoredKlubaften((s) => s.currentClubNightId === id ? s : { ...s, currentClubNightId: id }), []);
  const updateClubNight = useCallback((id: string, update: (n: ClubNight) => ClubNight) => updateStoredKlubaften((s) => ({ ...s, clubNights: s.clubNights.map((n) => n.id === id ? normalizeClubNight(update(n), n.id) : n), currentClubNightId: s.currentClubNightId ?? id })), []);
  const deleteClubNight = useCallback((id: string) => updateStoredKlubaften((s) => { const remaining = s.clubNights.filter((n) => n.id !== id); const next = s.currentClubNightId === id ? remaining.find((n) => n.status === "active") ?? remaining[0] ?? null : remaining.find((n) => n.id === s.currentClubNightId) ?? null; return { clubNights: remaining, currentClubNightId: next?.id ?? null }; }), []);
  const updateCurrent = useCallback((update: (n: ClubNight) => ClubNight) => { const id = getStoredKlubaften().currentClubNightId; if (id) updateClubNight(id, update); }, [updateClubNight]);
  const createClubNight = useCallback((input: { name: string; date: string; boardCount?: number; handicapBoards?: number[] }) => { const night = normalizeClubNight({ id: createId(), clubId: currentClubId, name: input.name.trim() || "Klubaften", date: input.date || todayIsoDate(), status: "active", boardCount: input.boardCount ?? 13, handicapBoards: input.handicapBoards ?? [], createdAt: new Date().toISOString() }, undefined, currentClubId); updateStoredKlubaften((s) => ({ clubNights: [night, ...s.clubNights], currentClubNightId: night.id })); return night; }, [currentClubId]);
  const setSelectedPlayers = useCallback((players: string[]) => updateCurrent((n) => ({ ...n, selectedPlayers: players })), [updateCurrent]); const setPools = useCallback((pools: Pool[]) => updateCurrent((n) => ({ ...n, pools })), [updateCurrent]); const setMatches = useCallback((matches: ClubMatch[]) => updateCurrent((n) => ({ ...n, matches })), [updateCurrent]); const setBoardCount = useCallback((boardCount: number) => updateCurrent((n) => ({ ...n, boardCount })), [updateCurrent]); const setHandicapBoards = useCallback((handicapBoards: number[]) => updateCurrent((n) => ({ ...n, handicapBoards })), [updateCurrent]);
  const finishClubNight = useCallback((id = getStoredKlubaften().currentClubNightId ?? undefined) => { if (!id) return; const finishedAt = new Date().toISOString(); updateStoredKlubaften((s) => { const nights = s.clubNights.map((n) => n.id === id ? normalizeClubNight({ ...n, status: "finished", finishedAt }, n.id, n.clubId ?? currentClubId) : n); saveLiveActiveSnapshotForClubNight(nights, currentClubId, id); return { ...s, clubNights: nights }; }); }, [currentClubId]); const abortClubNight = useCallback((id = getStoredKlubaften().currentClubNightId ?? undefined) => { if (id) updateClubNight(id, (n) => ({ ...n, status: "aborted", finishedAt: new Date().toISOString() })); }, [updateClubNight]); const finishKlubaften = useCallback(() => finishClubNight(), [finishClubNight]);
  const value = useMemo(() => ({ currentClubId, clubNights: scoped, activeClubNights: active, archivedClubNights: archived, isSharedStateReady, currentClubNightId: snapshot.currentClubNightId, currentClubNight: current, setCurrentClubNightId, createClubNight, updateClubNight, deleteClubNight, selectedPlayers: current?.selectedPlayers ?? EMPTY_CLUB_NIGHT.selectedPlayers, setSelectedPlayers, pools: current?.pools ?? [], setPools, matches: current?.matches.filter((m) => (m.clubId ?? currentClubId) === currentClubId) ?? [], setMatches, boardCount: current?.boardCount ?? 13, setBoardCount, handicapBoards: current?.handicapBoards ?? [], setHandicapBoards, isFinished: current?.status === "finished", finishKlubaften, finishClubNight, abortClubNight }), [currentClubId, scoped, active, archived, isSharedStateReady, snapshot.currentClubNightId, current, setCurrentClubNightId, createClubNight, updateClubNight, deleteClubNight, setSelectedPlayers, setPools, setMatches, setBoardCount, setHandicapBoards, finishKlubaften, finishClubNight, abortClubNight]);
  return <KlubaftenContext.Provider value={value}>{children}</KlubaftenContext.Provider>;
}
export function useKlubaften() { const context = useContext(KlubaftenContext); if (!context) throw new Error("useKlubaften must be used inside KlubaftenProvider"); return context; }
